Issue 44 fix
N0W0RK/TUM_GAD_Tests_SS21 pull request #47
Opened 2021-06-05 14:09 UTC by babyygemperor

**Shortly describe your proposed changes:**
 * https://github.com/N0W0RK/TUM_GAD_Tests_SS21/pull/45#pullrequestreview-676780843

**Link any issues if they have led to changes in the request:**
 * https://github.com/N0W0RK/TUM_GAD_Tests_SS21/issues/44

**Note the (sub-)exercises the tests are meant for:**

* GAD 06 - Verbessertes Sortieren

2021-06-05 14:18 UTC, CrsiX requested changes
Could you please address the code style issues mentioned by the GAD Worksheep? Especially the empty `if` and `else if` blocks  could be easily converted to one `if` statement with the `fail` call in it.

You don't need to address two style issues:
- max file length of more than 2000 lines
- max method length of more than 150 lines

Thanks

2021-06-05 14:30 UTC, N0W0RK commented
I am reconfiguring our codestyle guidelines but we should work on reducing file and method length. We might build a testhelper class that automates giant tests like in this file here

2021-06-05 14:43 UTC, CrsiX commented
Ideally, a good approach. But the problem might be: when you have a tool that generates test cases for something automatically, e.g. a function `f`, and also checks whether the results `f(x)` for certain `x` are correct, i.e. which provides `y=f(x)` _automatically_, how far are you away from building `f`? Because to accomplish this goal, you need to have some logic to know what's the right solution for a given `x`: you need to implement a way from `x` to `y`. And that's actually the students' tasks, so we **must not** do this.

2021-06-05 15:00 UTC, babyygemperor commented
> for a given x: you need to implement a way from x to y. And that's actually the students' tasks, so we must not do this.

That was actually my idea behind all my test, I highly approve this message. The pull request should be removed.


Side note:
> how far are you away from building f?

Unfortunately in English we don't use the term building for the respective German word "_Abbildung_", instead we say, the range/codomain (The set of solutions) or in this case, simply the output (or the image if we want to sound fancy)

2021-06-05 15:05 UTC, CrsiX commented
> The pull request should be removed.

Wait, you first approve my comment but then consider closing the PR. Why? Did I miss something here? :D

Yet another side note:

> Unfortunately in English we don't use the term building for the respective German word *"Abbildung"*, instead we say, the range/codomain (The set of solutions) or in this case, simply the output (or the image if we want to sound fancy)

Thanks for the explanation. My thoughts were actually more practically: 'building' refers to 'implementing' / 'constructing a function' :)

2021-06-05 15:13 UTC, babyygemperor commented
> Wait, you first approve my comment but then consider closing the PR. Why?

Because sleep is very essential part of human life, although it takes 33% of our life time, ignoring it leads to illogical/half finished sentences, with the hope that the reader has telepathic abilities. 

> My thoughts were actually more practically: 'building' refers to 'implementing' / 'constructing a function' :)

Ah okay, well in that case, "implementing"/"constructing a function" sounds more complete than "building". Building just sounded off in that sentence, hence my 2 cents

2021-06-05 15:16 UTC, N0W0RK commented
I have created #48 to further explaion and thack the progress of my proposal.

I am far from suggesting that we implement the actual solutions in our test. I rather want to streamline the process of having multiple array checks into a more clear and simple setup.

This PR imo does not need to be closed but simply fix the codestyle issue

2021-06-05 15:18 UTC, N0W0RK requested changes

2021-06-05 15:18 UTC, N0W0RK commented on GAD 6 - Verbessertes Sortieren/tests/simplesort/DualPivotFinderTester.java
>          assertArrayEquals(new int[]{1, 2}, DualPivotFinder.getMedianPivotFront(5).findPivot(arr, 1, 3));
This test also fits my issue but has not been fixed. There are a lot of lines like this

2021-06-05 16:25 UTC, babyygemperor commented
Done

2021-06-10 10:10 UTC, babyygemperor commented
All the issues have been fixed here since 5 days as well, I'm still waiting for someone to approve it.

2021-06-10 10:41 UTC, N0W0RK commented
I will merge if you resolve all codestyle issues associated with your changes

2021-06-10 23:26 UTC, babyygemperor commented
Done

2021-06-10 23:33 UTC, CrsiX commented
Thanks for addressing the issues lined out by us and the style checker. I will look into them again later :)

2021-06-10 23:39 UTC, N0W0RK approved these changes

2021-06-11 14:14 UTC, CrsiX approved these changes

2021-06-11 14:14 UTC, merged