Some tests for binomial heap
N0W0RK/TUM_GAD_Tests_SS21 pull request #56
Opened 2021-06-20 17:55 UTC by maharajamihir

Einfach paar tests für BinomialHeap.java

**Note the (sub-)exercises the tests are meant for:**

* GAD 8 - Binomial Heap: BinomialHeap.java

2021-06-20 19:42 UTC, N0W0RK requested changes
Generally fine tests. You should address all code style issues(they are all listed in the `Checks` section of your PR). I would also like you to address all comments I made on your additions. After all that, the PR should be able to merge.

2021-06-20 19:42 UTC, N0W0RK commented on GAD 8 - Binomial Heap/binomilia/HeapTester.java
> +		assertEquals(-300, heap.min());
Could you add an assertion message here?

2021-06-20 19:42 UTC, N0W0RK commented on GAD 8 - Binomial Heap/binomilia/HeapTester.java
> +		for (int i = -420; i < 1000; i++) {
The -420 (nice) makes the number of runs harder to count without any benefit. See also linea #139/#209/#218.

2021-06-20 19:42 UTC, N0W0RK commented on GAD 8 - Binomial Heap/binomilia/HeapTester.java
> +				size[0] = heap.size();
size() is not a default method in BinomialHeap. Please at least describe the functionality size should have so people can properly implement the method.

2021-06-20 19:42 UTC, N0W0RK commented on GAD 8 - Binomial Heap/binomilia/HeapTester.java
> +		Result myResult = new Result() {
Result classes should be generalized and in their own file, so that every test may use them.

2021-06-20 19:42 UTC, N0W0RK commented on GAD 8 - Binomial Heap/binomilia/HeapTester.java
> +	BinomialHeap heap = new BinomialHeap();
heap should be initialized separately for every test.

2021-06-20 19:42 UTC, N0W0RK commented on GAD 8 - Binomial Heap/binomilia/HeapTester.java
> +				steps.add(heap.size());
This would not allow adding trees in multiple steps.

2021-06-21 15:43 UTC, CrsiX requested changes
Thanks for the tests, they will provide some first help until #52 is ready, too :)

Two comments: 
- Could you please remove the file `HeapTester.java` as it's replaced by `BinomialHeapTester.java`?
- Could you move your files into a `test` directory? All other exercise tests are located in such a directory structure, too. Example for GAD 7 is `GAD 7 - Radixsort/tests/radix/`.

2021-06-21 15:45 UTC, CrsiX requested changes
Thanks for the tests, they will provide some first help until #52 is ready, too :)

Two comments: 
- Could you please remove the file `HeapTester.java` as it's replaced by `BinomialHeapTester.java`?
- Could you move your files into a `test` directory? All other exercise tests are located in such a directory structure, too. Example for GAD 7 is `GAD 7 - Radixsort/tests/radix/`.

2021-06-22 07:59 UTC, N0W0RK commented
Closed due to it being replaced by #57

2021-06-22 07:59 UTC, closed without merging